# symbols.py
# 🔹 List of all stock symbols for trading scripts
symbols = [
    "NIFTY",
    "BANKNIFTY","FINNIFTY", "MIDCPNIFTY",
    "360ONE", "ABCAPITAL", "ADANIENS", "ADANIGRE", "AMBUJAC", "ASHOKLEY", 
    "AUBANK", "AUROPHA", "AXISBANK", "BAJFINAN", "BANDHAN", "BANKBAR", 
    "BANKINDI", "BDL", "BEL", "BHEL", "BIOCON", "BPCL", "CAMS", "CANBK", 
    "CDSL", "CGPOWER", "CIPLA", "COALINDI", "COFORGE", "CONCOR", "CROMPTC", 
    "DABUR", "DELHIVERY", "DLF", "DRREDDY", "ETERNAL", "EXIDEIND", "FEDERALB", 
    "FORTIS", "GAIL", "GMRAIRPO", "GODREJCP", "HAVELLS", "HCLTECH", "HDFCBAN", 
    "HDFCLIFE", "HINDALCO", "HINDPETR", "HINDZINC", "HUDCO", "ICICIBANK", 
    "ICICIPRULI", "IDEA", "IDFCFIRST", "IEX", "INDHOTEL", "INDIANB", 
    "INDUSIND", "INDUSTOW", "INFY", "INOXWIND", "IOC", "IREDA", "IRFC", 
    "ITC", "JINDALSTE", "JIOFIN", "JSWENERG", "JSWSTEEL", "JUBLFOOD", 
    "KALYANKJ", "KFINTECH", "KOTAKBAN", "KPITTECH", "LAURUSLA", "LICHSGFIN", 
    "LICI", "LODHA", "LTF", "MANAPPU", "MARICO", "MAXHEAL", "MOTHERS", 
    "NATIONAI", "NAUKRI", "NBCC", "NESTLEIND", "NHPC", "NMDC", "NTPC", 
    "NUVAMA", "NYKAA", "OIL", "ONGC", "PATANJAL", "PAYTM", "PETRONET", 
    "PFC", "PGEL", "PIDILITIND", "PNB", "PNBHOUS", "POLICYBZ", "POWERGR", 
    "PPLPHARM", "PREMIERE", "PRESTIGE", "RBLBANK", "RECLTD", "RELIANCE", 
    "RVNL", "SAIL",  "SBICARD", "SBIN", "SHRIRAMP", "SONACOM", 
    "SUZLON", "SWIGGY", "SYNGENE", "TATACON", "TATAPOW", "TATASTEE", 
    "TATATECH", "TECHM", "TMPV", "UNIONBA", "UNITDSPR", "UNOMIND", "UPL", 
    "VBL", "VEDL", "WIPRO", "YESBANK", "ZYDUSLIFE"
    ]