# Generated by Django 6.0.1 on 2026-04-08 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trade_date', models.DateField(default=django.utils.timezone.now)),
                ('trade_type', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_spot', models.FloatField()),
                ('trigger_level', models.CharField(max_length=10)),
                ('trigger_price', models.FloatField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_spot', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(default='OPEN', max_length=20)),
                ('pnl', models.FloatField(default=0.0)),
            ],
        ),
    ]
