# Generated by Django 6.0.1 on 2026-04-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0002_papertrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionchain',
            options={},
        ),
        migrations.AddIndex(
            model_name='optionchain',
            index=models.Index(fields=['Symbol', 'Time'], name='mystock_opt_Symbol_04d242_idx'),
        ),
        migrations.AddIndex(
            model_name='optionchain',
            index=models.Index(fields=['Symbol', 'Strike_Price', 'Time'], name='mystock_opt_Symbol_ce1341_idx'),
        ),
        migrations.AddIndex(
            model_name='optionchain',
            index=models.Index(fields=['Symbol', 'Time', 'Strike_Price'], name='mystock_opt_Symbol_2b9814_idx'),
        ),
    ]
