# Generated by Django 6.0.1 on 2026-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0003_alter_optionchain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='entry_strike',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
