# Generated by Django 6.0.1 on 2026-04-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0004_papertrade_entry_strike'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_enabled', models.BooleanField(default=True)),
                ('default_target', models.FloatField(default=50.0)),
                ('default_sl', models.FloatField(default=50.0)),
                ('reversal_buffer', models.FloatField(default=5.0)),
            ],
            options={
                'verbose_name': 'Bot Setting',
                'verbose_name_plural': 'Bot Settings',
            },
        ),
    ]
