# Generated by Django 6.0.1 on 2026-04-23 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0007_init_synccontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionchain',
            options={'ordering': ['-Time']},
        ),
        migrations.RemoveIndex(
            model_name='optionchain',
            name='mystock_opt_Symbol_2b9814_idx',
        ),
        migrations.RenameIndex(
            model_name='papertrade',
            new_name='mystock_pap_trade_d_a9126a_idx',
            old_name='pt_date_result_idx',
        ),
        migrations.RenameIndex(
            model_name='papertrade',
            new_name='mystock_pap_symbol_bf57c4_idx',
            old_name='pt_symbol_result_idx',
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='result',
            field=models.CharField(db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='trade_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
