# Generated by Django 6.0.1 on 2026-04-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0008_alter_optionchain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='is_replay',
            field=models.BooleanField(default=False),
        ),
    ]
