# Generated by Django 6.0.1 on 2026-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0009_papertrade_is_replay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('resistance_status', models.CharField(choices=[('active', 'Active'), ('broken', 'Broken'), ('hold', 'Hold'), ('rejected', 'Rejected')], max_length=20, verbose_name='Resistance Status')),
                ('resistance_strike', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Resistance Strike')),
                ('resistance_strike2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='2nd Resistance Strike')),
                ('support_status', models.CharField(choices=[('active', 'Active'), ('broken', 'Broken'), ('hold', 'Hold'), ('rejected', 'Rejected')], max_length=20, verbose_name='Support Status')),
                ('support_strike', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Support Strike')),
                ('support_strike2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='2nd Support Strike')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10, verbose_name='Trade Type')),
                ('trade_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, verbose_name='Trade Level')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Journal',
                'verbose_name_plural': 'Trading Journals',
                'ordering': ['-created_at'],
            },
        ),
    ]
