# Generated by Django 6.0.1 on 2026-05-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0010_tradingjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingjournal',
            name='resistance_status',
            field=models.CharField(choices=[('wtt', 'WTT'), ('wtb', 'WTB'), ('strong', 'STRONG'), ('shifted_wtb', 'SHIFTED WTB'), ('shifted_wtt', 'SHIFTED WTT')], max_length=20, verbose_name='Resistance Status'),
        ),
        migrations.AlterField(
            model_name='tradingjournal',
            name='support_status',
            field=models.CharField(choices=[('wtt', 'WTT'), ('wtb', 'WTB'), ('strong', 'STRONG'), ('shifted_wtb', 'SHIFTED WTB'), ('shifted_wtt', 'SHIFTED WTT')], max_length=20, verbose_name='Support Status'),
        ),
        migrations.AlterField(
            model_name='tradingjournal',
            name='trade_level',
            field=models.CharField(choices=[('support_strike', 'Support Strike'), ('support_plus_strike', 'Support + Strike'), ('support_minus_strike', 'Support - Strike'), ('support2_strike', '2Support Strike'), ('support2_plus_strike', '2Support + Strike'), ('support2_minus_strike', '2Support - Strike'), ('resistance_strike', 'Resistance Strike'), ('resistance_plus_strike', 'Resistance + Strike'), ('resistance_minus_strike', 'Resistance - Strike'), ('resistance2_strike', '2Resistance Strike'), ('resistance2_plus_strike', '2Resistance + Strike'), ('resistance2_minus_strike', '2Resistance - Strike')], max_length=30, verbose_name='Trade Level'),
        ),
        migrations.AlterField(
            model_name='tradingjournal',
            name='trade_type',
            field=models.CharField(choices=[('call', 'CALL'), ('put', 'PUT')], max_length=10, verbose_name='Trade Type'),
        ),
    ]
