# Generated by Django 6.0.1 on 2026-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0012_rename_mystock_opt_symbol_04d242_idx_idx_oc_symbol_time_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='livesrdata',
            name='idx_sr_symbol_time_asc',
        ),
        migrations.RenameIndex(
            model_name='optionchain',
            new_name='idx_oc_symbol_time',
            old_name='mystock_opt_Symbol_04d242_idx',
        ),
        migrations.RenameIndex(
            model_name='optionchain',
            new_name='idx_oc_symbol_strike_time',
            old_name='mystock_opt_Symbol_ce1341_idx',
        ),
        migrations.RenameIndex(
            model_name='papertrade',
            new_name='idx_pt_date_result',
            old_name='mystock_pap_trade_d_a9126a_idx',
        ),
        migrations.RenameIndex(
            model_name='papertrade',
            new_name='idx_pt_symbol_result',
            old_name='mystock_pap_symbol_bf57c4_idx',
        ),
        migrations.RenameIndex(
            model_name='supportresistance',
            new_name='idx_sr_symbol_time',
            old_name='Support_Res_Symbol_a05ee6_idx',
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['symbol', 'trade_date', 'result'], name='idx_pt_core'),
        ),
        migrations.AddIndex(
            model_name='supportresistance',
            index=models.Index(fields=['Symbol', 'Time'], name='idx_sr_symbol_time_asc'),
        ),
    ]
