# Generated by Django 6.0.1 on 2026-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0013_remove_livesrdata_idx_sr_symbol_time_asc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='user_name',
            field=models.CharField(default='सर', max_length=50),
        ),
    ]
