# Generated by Django 6.0.1 on 2026-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0014_botsettings_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='entry_ltp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='exit_ltp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='lot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='pnl_rupees',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
