"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# from dotenv import load_dotenv
# load_dotenv(Path(__file__).resolve().parent / '.env')


# Load environment variables from .env file (Render के लिए सुरक्षित)
try:
    from dotenv import load_dotenv
    # यह आपके प्रोजेक्ट के मुख्य फोल्डर से .env को लोड करेगा
    load_dotenv(BASE_DIR / '.env') 
except ImportError:
    # Render पर यह पैकेज नहीं होगा, तो यह चुपचाप आगे बढ़ जाएगा
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os, dj_database_url

# ── Secret Key — Render पर Environment Variable से आएगा ──────────────────
SECRET_KEY = os.environ.get('SECRET_KEY')

# ── Debug — Render पर False, local पर True ───────────────────────────────
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'opchain-pbl1.onrender.com',
    'localhost',
    '127.0.0.1',
]

# Render HTTPS redirect
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT     = False  # Render का LB already handle करता है
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True

# DEBUG = True

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mystock',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # SecurityMiddleware के ठीक बाद — correct order
    'django.middleware.gzip.GZipMiddleware',       # ← NEW: 125KB → ~12KB (90% compression!)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mystock.middleware.KickOutMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'myproject.asgi.application'
ASGI_THREADS = 20  # Default ~5 से बढ़ाएं — polling APIs के लिए ज़रूरी

WSGI_APPLICATION = 'myproject.wsgi.application'



# ── Database ─────────────────────────────────────────────────────────────
# Render पर DATABASE_URL environment variable set करें
# Local dev पर SQLite automatically use होगा
_db_url = os.environ.get('DATABASE_URL')

if _db_url:
    # Render / Production: PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=_db_url,
            conn_max_age=0,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    # Local Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'timeout': 20,
                'init_command': (
                    'PRAGMA journal_mode=WAL;'
                    'PRAGMA synchronous=NORMAL;'
                    'PRAGMA cache_size=-32000;'
                    'PRAGMA temp_store=MEMORY;'
                    
                ),
                
            }
        }
    }



# ── Cache — LocMem (Redis हटाया, Render पर ज़रूरी नहीं) ────────────────────
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#         "LOCATION": "opchain-cache",
#     }
# }
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         'LOCATION': 'mystock_cache_table', # यह डेटाबेस में बनने वाली नई टेबल का नाम है
#     }
# }

import os

# Render के Environment Variables से Redis URL लेना
# REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": REDIS_URL,
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             # यह सेटिंग सुनिश्चित करती है कि अगर Redis क्रैश हो जाए, तो वेबसाइट क्रैश न हो
#             "IGNORE_EXCEPTIONS": True, 
#         }
#     }
# }

import os

IS_ON_RENDER = 'RENDER' in os.environ
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

CACHES = {
    # 1. मुख्य कैश (Redis)
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,  # 🟢 यह बहुत ज़रूरी है! Redis फेल होने पर एरर नहीं देगा
        }
    },
    # 2. बैकअप कैश (Database)
    "db_cache": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "mystock_cache_table",
    }
}
# websocket के लिए channels का ASGI application सेट करें
CHANNEL_LAYERS = {
    "default": {
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],  # 👈 यहाँ REDIS_URL डाल दें (ताकि यह Render का Redis यूज़ करे)
        },
    },
}

from mystock.credentials import access_token

UPSTOX_ACCESS_TOKEN = access_token

# जो symbols हर 1 minute fetch होंगे:
WATCHED_INSTRUMENTS = [
    {"instrument_key": "NSE_INDEX|Nifty 50",   "unit": "minutes", "interval": "1"},
    {"instrument_key": "NSE_INDEX|Nifty 50",   "unit": "minutes", "interval": "5"},
    {"instrument_key": "NSE_INDEX|Nifty Bank", "unit": "minutes", "interval": "5"},
    {"instrument_key": "NSE_INDEX|Nifty Bank", "unit": "minutes", "interval": "1"},
    # और symbols जोड़ते जाएं...
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

# TIME_ZONE = 'UTC'

# USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# # लॉगिन के लिए डिफ़ॉल्ट URL
# LOGIN_URL = '/accounts/login/'

# # लॉगिन सफल होने के बाद कहाँ जाना है (अगर URL में ?next= नहीं है तो)
# LOGIN_REDIRECT_URL = '/admin-panel/' 

# # लॉगआउट होने के बाद कहाँ जाना है
# LOGOUT_REDIRECT_URL = '/accounts/login/'

# लॉगिन पेज का रास्ता (urls.py में दिए गए नाम के अनुसार)
LOGIN_URL = 'login'

# लॉगिन सफल होने के बाद फॉलबैक रास्ता (View के काम न करने पर बैकअप के लिए)
LOGIN_REDIRECT_URL = 'dashboard'

# लॉगआउट होने के बाद सीधे लॉगिन पेज पर भेजने के लिए
LOGOUT_REDIRECT_URL = 'login'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ═══════════════════════════════════════════════════════
# यह block settings.py के END में add करें
# ═══════════════════════════════════════════════════════

# ── Broken Pipe filter: dev server पर harmless warning suppress करता है ──
import logging

class _IgnoreBrokenPipe(logging.Filter):
    """
    Django dev server पर 'Broken pipe' warning आती है जब browser
    page reload/navigate करता है और in-flight request cancel होती है।
    Production (gunicorn/uvicorn) पर यह नहीं आती — यहाँ सिर्फ suppress करें।
    """
    def filter(self, record):
        msg = record.getMessage()
        return "Broken pipe" not in msg and "broken pipe" not in msg.lower()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "ignore_broken_pipe": {
            "()": _IgnoreBrokenPipe,
        },
    },
    "formatters": {
        "simple": {
            "format": "[{levelname}] {name} — {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["ignore_broken_pipe"],
        },
    },
    "loggers": {
        "mystock": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # django.server = dev runserver का access log (Broken pipe यहाँ से आती है)
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
            "filters": ["ignore_broken_pipe"],
        },
    },
}



# अपनी कॉपी की हुई Groq Key यहाँ पेस्ट करें
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
